### PR TITLE
Add a nox file and additional linters

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds a *nox* file to the repository to automate routine maintenance tasks like running the linters (and adds new linters) and the tests. I've also removed some newly-found lint, which was mostly *black*-style issues with the notebooks. One bit of lint I haven't removed is to save the notebooks in a clean state (i.e. save with the output cleared). I think we should probably do this but I wanted to double-check with you, @mdpiper.

The *nox* file has a few sessions:
* `test`: run pytest on the repository
* `test-notebooks`: ensure that all of the notebooks run without failing
* `lint`: run the linters
* `clean`: remove generated files
* `clean-checkpoints`: remove _jupyter_ checkpoint files

Some of the notebooks are failing right now but I think that's mostly because of missing data files. I'll need to have a closer look.

This is still a work in progress.

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen This is great! Thank you for your help with this.

**Comment by mdpiper** [comment]
And I agree, the notebooks should be saved in a clean state.

**Comment by mdpiper** [comment]
On data files--I'd eventually like all data to reside in the top-level `data` directory, moving such files out of individual lesson dirs. This might be a task for a separate PR. Plus, I should make an issue for this.

**Comment by mcflugen** [comment]
Well this turned out the be a larger pull request than I had intended. Sorry about that @mdpiper.

I ended up doing the opposite of what you suggested by moving notebook data next to the notebooks that use them. I hope that's ok.

There are now *media* and *data* folders next to notebooks, which allows those lessons to be self-contained since the data are available regardless of where a user starts up the notebook. The only file I left in the top-level *media* folder is the logo since it's used by many notebooks. All of the notebooks now reference that file as a url (rather than a relative path name) so users will have to be connected to the internet to see the logo.

There were a good number of data and media files that weren't being used so I removed them. I think another benefit of moving the data/media files next to the notebooks is that it makes it more clear where they are being used and will, I hope, make it easier to keep unused files out of the repository.

All of the tests are now passing but I've excluded about a half-dozen notebooks from the testing (you can see the list in *pytest.ini*) for various reason (missing data, incomplete notebooks meant to be filled-out live).

Anyway, sorry for all the changes but I think this is ready to go now. Please let me know if you want me to undo any of the changes, I'm happy to do so.

**Comment by mdpiper** [comment]
@mcflugen I'll have to make some changes to the lessons. May I have push access to your branch?

**Comment by mcflugen** [comment]
> @mcflugen I'll have to make some changes to the lessons.

Thank you! I can also help with this if you like.

> May I have push access to your branch?

I think you should already.

**Comment by mdpiper** [comment]
@mcflugen The best-practices/continuous-integration.md lesson could use some tlc, if you'd like to take a try at it.

**Comment by mcflugen** [comment]
> @mcflugen The best-practices/continuous-integration.md lesson could use some tlc, if you'd like to take a try at it.

As part of this pull request?

**Review by mdpiper — APPROVED** [review]

**Comment by mdpiper** [comment]
👍

**Pull request merged**
