### PR TITLE
Add additional linters

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request adds some additional hooks to help with notebook lint.

New hooks check that:

* solution cells within a notebook are hidden with a `<details>` tag
* file names don't contain spaces
* headings within a notebook are consistent (for example, a level 1 heading isn't immediately followed by a level 3 heading)
* a notebook's kernel spec matches a given spec (for now, `name=python3` and `language=python`)

### CODE REVIEW

**Comment by mcflugen** [comment]
@mdpiper I notice that some notebooks have a kernel that refers to `csdms` while most are `python3`. Should we update them all of the notebooks to be one of these? Should some notebooks use a different kernel (e.g. *Landlab* notebooks should open in the *landlab* kernel)?

**Comment by mdpiper** [comment]
@mcflugen Ah, what we should do is make all of the kernels *Ivy*. I could attach a note on user-defined kernels to the Jupyter lesson.

**Comment by mcflugen** [comment]
> Ah, what we should do is make all of the kernels Ivy

I've updated the hook so that it will change all the notebook kernels to `display_name=Ivy` and `name=ivy`.

**Comment by mcflugen** [comment]
@mdpiper Ugh. I inadvertently added a whole bunch of files to the repository that shouldn't be in version control (mostly output files generated by notebooks but also some other random files). I've removed them from this pull request but I think I'll probably open up a new, clean, pull request so these files don't become part of our history on *csdms/ivy*.

**Review by mdpiper — APPROVED** [review]

**Comment by mcflugen** [comment]
Superseded by #123.

**Pull request closed without merging**
